import { execSync, spawn } from "node:child_process";
import { existsSync, writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import { homedir } from "node:os";
import { createServer } from "node:net";

const UMBRAL_DIR = join(homedir(), ".umbral");
const COMPOSE_PATH = join(UMBRAL_DIR, "docker-compose.yml");
const DOCKER_IMAGE = process.env.UMBRAL_IMAGE ?? "ghcr.io/josephrobles23/umbral-web:latest";

interface StartOptions {
  port?: string;
  detach?: boolean;
}

function dockerInstalled(): boolean {
  try {
    execSync("docker --version", { stdio: "ignore" });
    return true;
  } catch {
    return false;
  }
}

function composeInstalled(): boolean {
  try {
    execSync("docker compose version", { stdio: "ignore" });
    return true;
  } catch {
    return false;
  }
}

function findFreePort(start: number): Promise<number> {
  return new Promise((resolve, reject) => {
    const server = createServer();
    server.listen(start, "127.0.0.1", () => {
      const addr = server.address();
      const port = typeof addr === "object" && addr ? addr.port : start;
      server.close(() => resolve(port));
    });
    server.on("error", () => {
      if (start < 65535) resolve(findFreePort(start + 1));
      else reject(new Error("No free port found"));
    });
  });
}

function generateCompose(webPort: number, wsPort: number): string {
  const dbPath = join(UMBRAL_DIR, "umbral.db").replace(/\\/g, "/");
  const dbDir = UMBRAL_DIR.replace(/\\/g, "/");

  return `# Auto-generated by Umbral CLI — do not edit manually
name: umbral

services:
  neo4j:
    image: neo4j:5-community
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/umbral-dev
    volumes:
      - neo4j-data:/data
    healthcheck:
      test: ["CMD", "neo4j", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    image: ${DOCKER_IMAGE}
    ports:
      - "${webPort}:3000"
      - "${wsPort}:3099"
    environment:
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: umbral-dev
      UMBRAL_WS_PORT: "3099"
      UMBRAL_DB_PATH: /data/umbral.db
    volumes:
      - "${dbDir}:/data"
    depends_on:
      neo4j:
        condition: service_healthy

volumes:
  neo4j-data:
`;
}

export async function startCommand(options: StartOptions): Promise<void> {
  const w = (s: string) => process.stdout.write(s);

  w("\n  Umbral  —  Iniciando plataforma\n\n");

  if (!dockerInstalled()) {
    w("  ✗ Docker no esta instalado.\n");
    w("    Instala Docker Desktop: https://docs.docker.com/get-docker/\n\n");
    process.exit(1);
  }

  if (!composeInstalled()) {
    w("  ✗ Docker Compose no esta disponible.\n");
    w("    Actualiza Docker Desktop o instala el plugin Compose.\n\n");
    process.exit(1);
  }

  w("  ✓ Docker detectado\n");

  const webPort = options.port ? parseInt(options.port, 10) : await findFreePort(3000);
  const wsPort = await findFreePort(webPort + 99);

  mkdirSync(UMBRAL_DIR, { recursive: true });

  const compose = generateCompose(webPort, wsPort);
  writeFileSync(COMPOSE_PATH, compose, "utf-8");
  w(`  ✓ docker-compose.yml generado\n`);

  w("  ⟳ Descargando imagenes y levantando servicios...\n\n");

  const detach = options.detach !== false;

  try {
    if (detach) {
      execSync(`docker compose -f "${COMPOSE_PATH}" up -d`, {
        stdio: "inherit",
      });
    } else {
      const child = spawn("docker", ["compose", "-f", COMPOSE_PATH, "up"], {
        stdio: "inherit",
      });
      child.on("close", (code) => process.exit(code ?? 0));
      return;
    }
  } catch {
    w("\n  ✗ Error al iniciar los servicios.\n");
    w("    Revisa que Docker Desktop este corriendo.\n\n");
    process.exit(1);
  }

  w(`\n  ✓ Umbral corriendo\n`);
  w(`    Dashboard:  http://localhost:${webPort}\n`);
  w(`    Neo4j:      http://localhost:7474\n`);
  w(`    WebSocket:  ws://localhost:${wsPort}\n\n`);
  w(`  Para detener:  umbral stop\n\n`);
}
